### ISSUE TITLE
Error creating more than 2 users

### ISSUE THREAD

**Issue by berniemoran** [etsy/411#108] opened 2017-02-19 22:28 UTC
With version 1.2.0, can create the first 2 users without problem. When creating the 3rd user I get the following error:

PDOException: "SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.site_id, users.api_key" at [/var/www/411/phplib/DB.php:103] 0:[PDOStatement->execute() called at [/var/www/411/phplib/DB.php:103]] 1:[FOO\\DB::query() called at [/var/www/411/phplib/Model.php:140]] 2:[FOO\\Model->create() called at [/var/www/411/phplib/Model.php:116]] 3:[FOO\\Model->store() called at [/var/www/411/phplib/REST/Models.php:94]] 4:[FOO\\Models_REST->create() called at [/var/www/411/phplib/REST/Users.php:51]] 5:[FOO\\Users_REST->POST() called at [/var/www/411/phplib/REST.php:108]] 6:[FOO\\REST->route() called at [/var/www/411/htdocs/api/users.php:6

Is there somewhere I can debug this?

**Comment by ChristiaanDouma** [comment] 2017-02-20 07:51
This is a duplicate of #104

**Comment by kiwiz** [comment] 2017-02-20 18:21
Hi, is this from a clean install or after an upgrade?

**Comment by kiwiz** [comment] 2017-02-22 16:57
Fixed!

**Closed by kiwiz** 2017-02-22 16:57 UTC
