### ISSUE TITLE
Hyphens in field names

### ISSUE THREAD

**Issue by gregadams4** [etsy/411#19] opened 2016-09-21 18:05 UTC
I receive the following error when trying to query field names that have a hyphen in them. Have tried a few ways around it i.e. escaping and such and only to be given other errors. Just curious if this is expected behaviour, if there is a way around it, or if we could get a bug fix. Almost all my fields have hyphens, works fine on any fields that don't. sad face. 

Query given:

os-cpu-one:>10

Error Thrown:

Error: Catch all: Expected ":" or [a-zA-Z0-9._] but "-" found.

**Comment by kiwiz** [comment] 2016-09-21 19:23
@gregadams4 Expected behaviour, but only because don't have any fields with hyphens. :]

I've just pushed a fix for this. It should work as long as your field name doesn't start with a hyphen.

**Comment by gregadams4** [comment] 2016-09-21 19:29
Can confirm this push worked :)

Thank you sir.

**Closed** 2016-09-21 19:30 UTC
